CONFIG_GPIO=y
CONFIG_LOG=y

CONFIG_LED_STRIP=y
CONFIG_WS2812_STRIP_GPIO=y

CONFIG_SPI=y
CONFIG_WS2812_STRIP_SPI=y

CONFIG_SERIAL=y
CONFIG_UART_CONSOLE=y

CONFIG_BLINK_SLEEP_250MS=y

# Iomico lecture 4 homework task dummy config
# LED Subsystem
CONFIG_LED_SUBSYSTEM=y

# Advanced LED features
CONFIG_ADV_LED=y
CONFIG_LED_BRIGHTNESS=100
CONFIG_LED_FADE_MS=500